IMAGE = "debian/bookworm64"
MEMORY = 1024
CPUS = 1

Vagrant.configure("2") do |config|
  vm_configs = [
    { hostname: "cpaluszeS", ip: "192.168.56.110" },
    { hostname: "cpaluszeSW", ip: "192.168.56.111" }
  ]

  vm_configs.each do |vm|
    config.vm.define vm[:hostname] do |node|
      node.vm.box = IMAGE
      node.vm.hostname = vm[:hostname]
      node.vm.network "private_network", ip: vm[:ip]

      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "1024"
        vb.cpus = CPUS
        vb.name = vm[:name]
      end
    end
  end
end
